### ISSUE TITLE
Deserialization structs

### ISSUE THREAD

**Issue by emj1z3** [kgeronim/cbpro#1]
Thank you for the great work on this crate! I was using coinbase-pro-rs, but needed something with full async support.

I was wondering if you have any plans to introduce the serde deserialization structs to this project, possibly by permission/collaboration from that crate's author. I currently have it working by having just copied/updated some of the code from coinbase-pro-rs in my local project.

**Comment by kgeronim** [comment]
Hi,

Thanks for the feedback, I did just that on a new project I’ll be releasing. Is an async wrapper to binance.
Ill carry over the new design I used for the binance wrapper over to cbpro soon. I realized forcing the return of serde_json::Value is too restrictive.

Regards,
Kevin

________________________________
